### PR TITLE
refactor(loader): fix warnings by 'cargo clippy' for loader

### PR DESCRIPTION
**Pull request by octonawish-akcodes**
#### 1. Does this PR affect any open issues?(Y/N) and add issue references (e.g. "fix #123", "re #123".):

- [ ] N
- [x] Y 

issue #191 
#### 2. What is the scope of this PR (e.g. component or file name):

Refactor KCLVM/loader
image

Not sure about the warning, maybe its giving a warning to update the rust version in the code? @Peefy

### CODE REVIEW

**Comment by octonawish-akcodes** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by octonawish-akcodes** [comment]
recheck

**Comment by Peefy** [comment]
Good Job! LGTM!

The reason for the warning is that the [rust-crypto](https://github.com/DaGenix/rust-crypto) library is a [dependency](https://github.com/kcl-lang/kcl/blob/main/kclvm/config/Cargo.toml#L17) of `kclvm/config` crate, but it has not been maintained for a long time and adopts the old Rust syntax. One alternative is to replace it with another library. PRs Welcome!

**Review by Peefy — APPROVED** [review]
LGTM

**Pull request merged**
