### PR TITLE
refactor(error): fix warnings by 'cargo clippy' for error

### PR DESCRIPTION
**Pull request by octonawish-akcodes**
#### 1. Does this PR affect any open issues?(Y/N) and add issue references (e.g. "fix #123", "re #123".):

- [ ] N
- [x] Y 

issue #191 
#### 2. What is the scope of this PR (e.g. component or file name):

KCLVM/error

### CODE REVIEW

**Review by Peefy — APPROVED** [review]
LGTM

**Comment by octonawish-akcodes** [comment]
Is there any IRC channel like slack or something? @Peefy

**Comment by octonawish-akcodes** [comment]
Dont merge it yet, there is an issue in the commit.

**Comment by Peefy** [comment]
> Is there any IRC channel like slack or something? @Peefy 

See https://github.com/kcl-lang/community to join our slack. Welcome!

**Pull request merged**
