### PR TITLE
added GitHub action support for building and testing as KCL on Linux …

### PR DESCRIPTION
**Pull request by octonawish-akcodes**
#### 1. Does this PR affect any open issues?(Y/N)

- [ ] N
- [x] Y 

Added the Linux ci part  for issue

### CODE REVIEW

**Comment by octonawish-akcodes** [comment]
I am not sure whats wrong im doing here, according to me it should've got the `Makefile` from the topmost directory but it isn't  getting its location from the image it pulled from the registry of kcllang of arm64, @Peefy can you help here?

**Comment by Peefy** [comment]
> I am not sure whats wrong im doing here, according to me it should've got the `Makefile` from the topmost directory but it isn't getting its location from the image it pulled from the registry of kcllang of arm64, @Peefy can you help here?

Thank you for your contribution. I will take a look.

**Comment by Peefy** [comment]
Seems to lost the checkout action:

```
      - name: Check out code
        uses: actions/checkout@v3
        with:
          submodules: "true"
```

**Comment by octonawish-akcodes** [comment]
According to the CI Run `cargo` is there 
image
I am not sure why its still complaining, I also tried exporting the PATH of it explicitly after the rust toolchain installation but still didn't worked out,

```
Run docker run --rm --platform linux/arm64 \
/workspace/run.sh -a build
/workspace/scripts/build.sh: line 26: cargo: command not found
make: *** [Makefile:26: build] Error [1](https://github.com/kcl-lang/kcl/actions/runs/7771608343/job/21193110606?pr=1023#step:9:1)27
Error: Process completed with exit code 2.
```

cc @Peefy

**Comment by Peefy** [comment]
LGTM! @octonawish-akcodes Dot worry, I'll fix it and I've merged this PR.

**Review by Peefy — APPROVED** [review]

**Pull request merged**
