### PR TITLE
refactor(lexer): fix warnings by 'cargo clippy' for lexer

### PR DESCRIPTION
**Pull request by octonawish-akcodes**
#### 1. Does this PR affect any open issues?(Y/N) and add issue references (e.g. "fix #123", "re #123".):

- [ ] N
- [x] Y 

issue #191 

#### 2. What is the scope of this PR (e.g. component or file name):

KCLVM/lexer

Before:
image

After:
image

### CODE REVIEW

**Comment by Peefy** [comment]
@octonawish-akcodes Could you fix the formatting issues in CI using cargo fmt?

**Comment by octonawish-akcodes** [comment]
> @octonawish-akcodes Could you fix the formatting issues in CI using cargo fmt?

Yes, I was fixing that. Done.

**Review by Peefy — APPROVED** [review]
LGTM

**Comment by octonawish-akcodes** [comment]
There is a test failure for the compiler base I was inspecting that but didn't understand.

**Pull request merged**
